version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estatedb
  scraper:
    build: ./scraper
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.cz
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
  server:
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - 8080:80
    depends_on:
      - server
